---
title: "Homework 3"
output: flexdashboard::flex_dashboard
runtime: shiny
---


```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(rmarkdown)
library(knitr)
library(Hmisc)
library(DT)

library(data.table)
assignInNamespace("cedta.override", value = c(data.table:::cedta.override,"rmarkdown"), ns = "data.table")


opts_chunk$set(echo = FALSE, comment="", warning = FALSE, message = FALSE, tidy.opts=list(width.cutoff=55), tidy = TRUE)

```


```{r read_data, include=FALSE, eval = TRUE}
setwd("~/Applied Data Science/hw3/data")
dat <- fread(input = "../Data/Homework 3 Data.csv", verbose = FALSE)
```


```{r constants}
id.name <- "id"
age.name <- "Age"
gender.name <- "Gender"
income.name <- "Income"
region.name <- "Region"
persona.name <- "Persona"

product.name <- "Product"
awareness.name <- "Awareness"
consideration.name <- "Consideration"
consumption.name <- "Consumption"
satisfaction.name <- "Satisfaction"
advocacy.name <- "Advocacy"
aggregated.engagement.name <- "Aggergated.Engagement"

pattern.bp <- "BP_"

age.group.name <- "Age Group"
income.group.name <- "Income Group"

cuts.age <- c(18, 35, 50, 65, 120)
cuts.income <- 1000* c(0, 50, 75, 100, 150, 250)

dat[, eval(age.group.name) := cut2(x = get(age.name), cuts = cuts.age)]
dat[, eval(income.group.name) := cut2(x = get(income.name), cuts = cuts.income)]
dat[, eval(satisfaction.name) := get(satisfaction.name)/10]

unique.age.groups <- dat[, unique(get(age.group.name))]
unique.genders <- dat[, unique(get(gender.name))]
unique.income.groups <- dat[, unique(get(income.group.name))]
unique.regions <- dat[, unique(get(region.name))]
unique.personas <- dat[, unique(get(persona.name))]
unique.products <- dat[, unique(get(product.name))]
num.products <- length(unique.products)

respondent.variables <- c(age.group.name, gender.name, income.group.name, region.name, persona.name)
states.of.engagement <- c(awareness.name, consideration.name, consumption.name, satisfaction.name, advocacy.name)
bp.traits <- names(dat)[grep(pattern = pattern.bp, x = names(dat))]
negative_perceptions <- names(dat)[17:20]
```

```{r functions}
percentage.table <- function(x, digits = 1){
  tab <- table(x)
  percentage.tab <- 100*tab/(sum(tab))
  rounded.tab <- round(x = percentage.tab, digits = digits)
  return(rounded.tab)
}

round.numerics <- function(x, digits){
  if(is.numeric(x)){
    x <- round(x = x, digits = digits)
  }
  return(x)
}
mean.diff <- function(x, y){
  return(mean(x, na.rm=TRUE) - mean(y, na.rm=TRUE))
}

percentage.mark <- function(x, digits = 1)
{
  percentage <- 100*x/dat[,.N]
  rounded.percentage <- round(x = percentage, digits = digits)
  return(sprintf("%.1f %%", rounded.percentage))
}

# Reference form the lecture note 8. 

engagement.model <- function(dt, outcome.name, input.names, model.type){
  res <- fit.model(dt = dt, outcome.name = outcome.name, input.names = input.names, model.type = model.type)
  return(res)
}

fit.model <- function(dt, outcome.name, input.names, model.type, digits = 3){
  the.formula <- reduce.formula(dt = dt, outcome.name = outcome.name, input.names = input.names)
  
  if(model.type == "logistic"){
    mod <- glm(formula = the.formula, family = "binomial", data = dt)
    mod.summary <- logistic.regression.summary(glm.mod = mod, digits = digits)
  }
  if(model.type == "linear"){
    mod <- lm(formula = the.formula, data = dt)
    mod.summary <- linear.regression.summary(glm.mod = mod, digits = digits)
  }
  mod.summary.rounded <- mod.summary[, lapply(X = .SD, FUN = "round.numerics", digits = digits)]
  return(mod.summary.rounded)
}

logistic.regression.summary <- function(glm.mod, digits = 3){
  library(data.table)
  glm.coefs <- as.data.table(summary(glm.mod)$coefficients, keep.rownames = TRUE)
  alpha = 0.05
  z <- qnorm(p = 1-alpha/2, mean = 0, sd = 1)
  glm.coefs[, Odds.Ratio := exp(Estimate)]
  glm.coefs[, OR.Lower.95 := exp(Estimate - z * `Std. Error`)]
  glm.coefs[, OR.Upper.95 := exp(Estimate + z * `Std. Error`)]
  return(glm.coefs[])
}



linear.regression.summary <- function(lm.mod, digits = 3){
  library(data.table)
  lm.coefs <- as.data.table(summary(lm.mod)$coefficients, keep.rownames = TRUE)
  alpha = 0.05
  z <- qnorm(p = 1-alpha/2, mean = 0, sd = 1)
  lm.coefs[, Coef.Lower.95 := Estimate - z * `Std. Error`]
  lm.coefs[, Coef.Upper.95 := Estimate + z * `Std. Error`]
  return(lm.coefs)
}

create.formula <- function(outcome.name, input.names, input.patterns = NA, all.data.names = NA, return.as = "character"){
  
  variable.names.from.patterns <- c()
  if(!is.na(input.patterns[1]) & !is.na(all.data.names[1])){
    pattern <- paste(input.patterns, collapse = "|")
    variable.names.from.patterns <- all.data.names[grep(pattern = pattern, x = all.data.names)]
  }
  all.input.names <- unique(c(input.names, variable.names.from.patterns))
  all.input.names <- all.input.names[all.input.names != outcome.name]
  
  if(!is.na(all.data.names[1])){
    all.input.names <- all.input.names[all.input.names %in% all.data.names]
  }

  input.names.delineated <- sprintf("`%s`", all.input.names)
  the.formula <- sprintf("`%s` ~ %s", outcome.name, paste(input.names.delineated, collapse = "+"))
  
  if(return.as == "formula"){
    return(as.formula(the.formula))
  }
  if(return.as != "formula"){
    return(the.formula)
  }
}
reduce.formula <- function(dt, outcome.name, input.names, input.patterns = NA, max.input.categories = 20, max.outcome.categories.to.search = 4, return.as = "formula"){
  require(data.table)
  dt <- setDT(dt)
  
  if(!(outcome.name %in% names(dt))){
    return("Error:  outcome.name is not in names(dt).")
  }
  
  pattern.names <- list()
  if(!is.na(input.patterns[1])){
    for(i in 1:length(input.patterns)){
      pattern.names[[i]] <- names(dt)[grep(pattern = input.patterns[i], x = names(dt))]
    }
  }
  all.input.names <- c(input.names, as.character(pattern.names))
  
  num.outcome.categories <- dt[!is.na(get(outcome.name)), length(unique(get(outcome.name)))]
  
  if(num.outcome.categories <= max.outcome.categories.to.search){
    num.unique.tab <- dt[, lapply(X = .SD, FUN = function(x){return(length(unique(x[!is.na(x)])))}), .SDcols = input.names, by = outcome.name]
    min.categories.tab <- num.unique.tab[, lapply(X = .SD, FUN = "min"), .SDcols = input.names]
    
    reduced.inputs <- names(min.categories.tab)[min.categories.tab >= 2]
  }
  if(num.outcome.categories > max.outcome.categories.to.search){
    reduced.inputs <- all.input.names
  }
  
  the.formula <- create.formula(outcome.name = outcome.name, input.names = reduced.inputs, all.data.names = names(dt), input.patterns = NA, return.as = return.as)
  return(the.formula)
}

add.backtick <- function(x, include.backtick = "as.needed"){
  if(include.backtick == "all"){
    w <- 1:length(x)
  }
  if(include.backtick == "as.needed"){
    w <- grep(pattern = " ", x = x, fixed = TRUE)
  }  
  if(length(w) > 0){
    x[w] <- sprintf("`%s`", x[w])
  }

  return(x)
}
create.formula <- function(outcome.name, input.names, input.patterns = NA, all.data.names = NA, include.backtick = "as.needed", return.as = "formula"){
  
  variable.names.from.patterns <- c()
  if(!is.na(input.patterns[1]) & !is.na(all.data.names[1])){
    pattern <- paste(input.patterns, collapse = "|")
    variable.names.from.patterns <- all.data.names[grep(pattern = pattern, x = all.data.names)]
  }
  all.input.names <- unique(c(input.names, variable.names.from.patterns))
  all.input.names <- all.input.names[all.input.names != outcome.name]
  
  if(!is.na(all.data.names[1])){
    all.input.names <- all.input.names[all.input.names %in% all.data.names]
  }

  input.names.delineated <- add.backtick(x =  all.input.names, include.backtick = include.backtick)
  outcome.name.delineated <- add.backtick(x = outcome.name, include.backtick = include.backtick)
  the.formula <- sprintf("%s ~ %s", outcome.name.delineated, paste(input.names.delineated, collapse = "+"))
  
  if(return.as == "formula"){
    return(as.formula(the.formula))
  }
  if(return.as != "formula"){
    return(the.formula)
  }
}

```


Introduction
=====================================  

We are analyzing data from the Marketing Department covering a variety of mobile phone products.  

The survey was given to `r dat[, length(unique(get(id.name)))]` respondents and covered `r num.products` separate products.

Click on the tabs to see different reports.


Question 1
===================================


Row {data-height=500}
-------------------------------------

```{r respondents}
inputPanel(
  selectInput(inputId="respondent_variable", label = "Select Variable:", choices = respondent.variables, selected =  respondent.variables[1])
)


renderPlot({
  tab <- percentage.table(x = dat[get(product.name) == get(product.name)[1], get(input$respondent_variable)])
  barplot(height = tab, space=0.01, las = 1, main = input$respondent_variable, ylab = "Percentage", xlab = input$respondent_variable, ylim = c(0, 1.2*max(tab, na.rm = T)), col = "dodgerblue")
  
  space_val = 0
  text(x = -0.4 + 1:length(tab) * (1+space_val), y = tab, labels = sprintf("%.1f%%", tab), pos = 3)
})
```

Question 2
=====================================  


Row {data-height=800}
-------------------------------------

```{r products}
inputPanel(
  selectInput(inputId="product_state", label = "State of Engagement:", choices = states.of.engagement, selected = states.of.engagement[1]),
  selectInput(inputId="product_age_group", label = "Age Group", choices = unique.age.groups, selected = unique.age.groups, multiple = T),
  selectInput(inputId = "product_gender", label = "Gender", choices = unique.genders, selected = unique.genders, multiple = T),
  selectInput(inputId = "product_income_group", label = "Income Group", choices = unique.income.groups, selected = unique.income.groups, multiple = T),
  selectInput(inputId = "product_region", label = "Region", choices = unique.regions, selected = unique.regions, multiple = T),
  selectInput(inputId = "product_persona", label = "Persona", choices = unique.personas, selected = unique.personas, multiple = T),
  
  sliderInput(inputId = "Numb_products", label = "Numb of Products", min = 1, max = 20, value = 5, step = 1)
)

renderPlot({
  subdat <- dat[get(age.group.name) %in% input$product_age_group & get(gender.name) %in% input$product_gender & get(income.group.name) %in% input$product_income_group & get(region.name) %in% input$product_region & get(persona.name) %in% input$product_persona]
  
  rates <- subdat[, .(Mean = 100*mean(get(input$product_state), na.rm=T)), by = product.name]

  setorderv(x = rates, cols = "Mean", order = -1)
  
  sub_rates <- rates[1:input$Numb_products,]

  barplot <- barplot(height = sub_rates[,Mean], space=0.01, las = 1, main = sprintf("Rate of %s", input$product_state), ylab = sprintf("Rate of %s", input$product_state), ylim = c(0, 120), xaxt = "n", axes = F, col = "dodgerblue")
  axis(side = 2, at = 20*(0:5), las = 2)
  
  text(barplot, par("usr")[3], labels = sub_rates[, get(product.name)], srt = 45, adj = c(1.1,1.1), xpd = T)
  
  space_val = 0
  text(x = -0.4 + 1:sub_rates[,.N] * (1+space_val), y = sub_rates[,Mean], labels = sprintf("%.1f%%", sub_rates[, Mean]), pos = 3)
})
```


Question 3
=====================================  

Row {data-height=500}
-------------------------------------

```{r brand_perceptions}
inputPanel(
  selectInput(inputId= "bp_age_group", label = "Age Group", choices = unique.age.groups, selected = unique.age.groups, multiple = T),
  selectInput(inputId = "bp_gender", label = "Gender", choices = unique.genders, selected = unique.genders, multiple = T),
  selectInput(inputId = "bp_income_group", label = "Income Group", choices = unique.income.groups, selected = unique.income.groups, multiple = T),
  selectInput(inputId = "bp_region", label = "Region", choices = unique.regions, selected = unique.regions, multiple = T),
  selectInput(inputId = "bp_persona", label = "Persona", choices = unique.personas, selected = unique.personas, multiple = T),

  sliderInput(inputId = "bp_Top_products", label = "Numb of Products", min = 1, max = 20, value = 5, step = 1)
)

invert.score <- function(x){
  max = 10
  return(max-x)
}

renderPlot({
  subdat <- dat[get(age.group.name) %in% input$bp_age_group & get(gender.name) %in% input$bp_gender & get(income.group.name) %in% input$bp_income_group & get(region.name) %in% input$bp_region & get(persona.name) %in% input$bp_persona]
  
  bp.tab <- subdat[,lapply(X = .SD, FUN = "mean", na.rm = T), .SDcols = bp.traits, by = product.name]
  bp.neg.tab <- bp.tab[,lapply(X = .SD, FUN = 'invert.score'), .SDcols = negative_perceptions]
  
  bp.avg.tab <- cbind(bp.tab[,1:9],bp.neg.tab)
  bp.overall.tab <- bp.avg.tab[, .(Product = get(product.name), Overall_avg = rowMeans(bp.avg.tab[,2:13],na.rm = T))]
  setorderv(x = bp.overall.tab, cols = "Overall_avg",-1)
  selected.bp.overall <- bp.overall.tab[1:input$bp_Top_products]
  sub.bp.overall <- selected.bp.overall[, Overall_avg := round(x = Overall_avg, digits = 1)]

  barplot <- barplot(height = sub.bp.overall[,Overall_avg], space=0.01, las = 1, main = sprintf("Top %s brands' overall Average Perception", input$bp_Top_products), ylab = "Overall average perception", ylim = c(0, 12), xaxt = "n", axes = F, col = "dodgerblue")
  axis(side = 2, at = 2*(0:5), las = 2)
  
  text(barplot, par("usr")[3], labels = sub.bp.overall[, get(product.name)], srt = 45, adj = c(1.1,1.1), xpd = T)
  
  space_val = 0
  text(x = -0.4 + 1:sub.bp.overall[,.N] * (1+space_val), y = sub.bp.overall[,Overall_avg], labels = sub.bp.overall[,Overall_avg], pos = 3)

})

```

Question 4
=====================================  

Row {data-height=500}
-------------------------------------

```{r engagement_plots}
inputPanel(
  selectInput(inputId="em_first_outcome", label = "First Engagement:", choices = states.of.engagement, selected = states.of.engagement[1]),
  selectInput(inputId="em_second_outcome", label = "Second Engagement:", choices = states.of.engagement, selected = states.of.engagement[2]),
  sliderInput(inputId="em_digits", label = "Digits:", min = 1, max = 4, value = 2, step = 1),
  
  sliderInput(inputId = "em_Numb_products", label = "Numb of Products", min = 1, max = 20, value = 5, step = 1),

  checkboxInput(inputId = "em_show_percentages", label = "Show Percentages", value = T)

)


renderPlot({
  First.tab = dat[, .(First_rate = 100 * mean(get(input$em_first_outcome), na.rm = T)), by = product.name]
  
  Sec.tab = dat[, .(Sec_rate = 100 * mean(get(input$em_second_outcome), na.rm = T)), by = product.name]
  
  Subtab = merge(First.tab, Sec.tab, by = product.name)
  Subtab[, difference := First_rate - Sec_rate]
  setorderv(x = Subtab, cols = "difference", order = -1)
  
  Subtab.rounded = Subtab[, difference := round(x = difference, digits = input$em_digits)]
  
  selected.Subtab = Subtab.rounded[1:input$em_Numb_products,]

  barplot <- barplot(height = selected.Subtab[,difference], space=0.01, las = 1, main = sprintf("The Difference between %s and %s of top %s", input$em_first_outcome, input$em_second_outcome, input$em_Numb_products), ylab = "Differences as percentages", ylim = c(-60, 120), xaxt = "n", axes = F, col = "dodgerblue", cex.lab = 0.8, cex.axis = 0.8)
  axis(side = 2, at = 20*(0:5), las = 3)
  
  text(barplot, par("usr")[3], labels = selected.Subtab[,get(product.name)], srt = 45, adj = c(1.1,1.1), xpd = TRUE, cex = 0.8)

  if(input$em_show_percentages == T){
  space_val = 0
  text(x = -0.4 + 1:selected.Subtab[,.N] * (1+space_val), y = selected.Subtab[,difference], labels = paste0(selected.Subtab[,difference],"%"), cex = 0.8, pos = 3)
  }
  
})

```

Question 5
=====================================  

Row {data-height=300}
-------------------------------------


```{r engagement_models}
inputPanel(
  selectInput(inputId = "em_product", label = "Select Product:", choices = unique.products, selected = product.name[1]),
  
  selectInput(inputId = "em_state", label = "Select State of Engagement:", choices = states.of.engagement, selected = states.of.engagement[1]), 
  
  selectInput(inputId = "em_inputs", label = "Inputs:", choices = c(age.group.name, gender.name, income.group.name, region.name, persona.name, bp.traits, aggregated.engagement.name), selected = c(age.group.name, gender.name, income.group.name, region.name, persona.name, aggregated.engagement.name), multiple = T)
  
)

renderDataTable({
 
  Subtab = dat[get(product.name) == input$em_product, .SD, .SDcols = c(id.name, product.name, states.of.engagement, bp.traits, age.group.name, gender.name, income.group.name, region.name, persona.name)]
 
  Subtab2 = dat[get(product.name) != input$em_product, .(Aggergated.Engagement = mean(get(input$em_state), na.rm = T)), by = id.name]
 
  aggregated.tab <- merge(Subtab,Subtab2, by = id.name)
  
  if(input$em_state == satisfaction.name){
    model.type <- "linear"
  }
  if(input$em_state != satisfaction.name){
    model.type <- "logistic"
  }
  
  res <- fit.model(dt = aggregated.tab, outcome.name = input$em_state, input.names = input$em_inputs, model.type = model.type)
  
  
  datatable(data = res)
})

```

Row {data-height=700}
-------------------------------------
